[setting]

# 日志
[log]
    # 日志等级 all.全部日志, prod.一般日志(warning,error), alert.提示日志(warning,error,info), warning.警告日志, info.正常日志, error.错误日志
    level = "all"
    # 日志保存目录,会在此目录下生成一个当天的日志文件
    path = "logs"
    # 是否输出错误位置,转换出错时建议打开, 以便配合作者修复 BUG
    trace = false

# 数据库
[database]
    [[database.default]]
        host = "127.0.0.1"
        port = "3306"
        user = "root"
        pass = "123456"
        name = "comic"
        type = "mysql"
        debug = "true"

# 服务器
[server]
    ## HTTP 服务器
    [server.http]
        host = "0.0.0.0"
        port = "33001"

# 通知
[notice]
    # 0不使用, 1钉钉通知
    type = 0
    # 新书通知
    book = true
    # 新章节通知
    chapter = true
    # 接收人,如果是钉钉则用手机号, 若是全部则留空
    receiver = ""
    # ding_talk_token
    ding_talk_token = "8eaeec8ea1c97b646e85c89e884ff1cae5e5302991088f4a8d876268ce1bd59d"

# 图片配置
[image]
    # 是否图片本地化
    local = true
    # 图片保存路径
    path = "upload/images"
    # 图片名方式 md5 / normal
    # Bid-Cid-OrderId 或 md5(Bid-Cid-OrderId) 漫画ID-章节ID-排序ID
    nametype = "md5"
